/*
 * Copyright (C) 2010-2026, Danilo Pianini and contributors
 * listed, for each module, in the respective subproject's build.gradle.kts file.
 *
 * This file is part of Alchemist, and is distributed under the terms of the
 * GNU General Public License, with a linking exception,
 * as described in the file LICENSE in the Alchemist distribution's top directory.
 */

package it.unibo.alchemist.model.geospatial

import it.unibo.alchemist.model.Environment
import it.unibo.alchemist.model.GeoPosition
import it.unibo.alchemist.model.geospatial.reading.CdmGridSnapshots
import it.unibo.alchemist.model.geospatial.reading.GridSnapshots
import it.unibo.alchemist.model.geospatial.reading.RasterGrid
import it.unibo.alchemist.model.geospatial.strategy.bracketIndices
import it.unibo.alchemist.model.geospatial.strategy.missing.MissingValueStrategy
import it.unibo.alchemist.model.geospatial.strategy.missing.PropagateNull
import it.unibo.alchemist.model.geospatial.strategy.spatial.BilinearInterpolator
import it.unibo.alchemist.model.geospatial.strategy.spatial.SpatialInterpolationStrategy
import it.unibo.alchemist.model.geospatial.strategy.temporal.LinearInterpolation
import it.unibo.alchemist.model.geospatial.strategy.temporal.TemporalInterpolationStrategy
import it.unibo.alchemist.model.geospatial.strategy.weight
import java.nio.file.Path
import java.time.Duration
import java.time.Instant

/**
 * A [GeoLayer] that exposes a value of type [T] for any [GeoPosition] as a function
 * of the current simulation time, backed by temporal NetCDF/GRIB data.
 * On [getValue], the layer knows the perceived simulation time at that moment via
 * [Environment.simulationOrNull], so no reaction is needed to "advance" the layer.
 *
 * When [getValue] is called, the two time slices that enclose the current time are selected,
 * their values are evaluated using the [temporalInterpolation], [missingValue],
 * and they are blended using [temporalInterpolation].
 * If the simulation time falls outside the calculated simulation time range,
 * the returned value will refer to the first or last time slice of [data].
 *
 * Once the construction is complete, real-world time [Instant] are converted proportionally to
 * simulation time using [timeOrigin] and [timeScale].
 *
 * Two constructors are currently available (a third one is planned once the
 * `acquisition` subpackage is implemented. SEE THE TODO below):
 * - **Primary** (this): accepts a ready-built [GridSnapshots]; intended for unit tests.
 * - **Directory**: accepts a local [Path], builds [CdmGridSnapshots] internally (no network I/O).
 *
 * @property environment simulation environment. Used only to read the current time via [Environment.simulationOrNull].
 * @property data temporal raster series backing this layer.
 * @param timeOrigin real-world [Instant] corresponding to simulation `Time.ZERO`. Defaults to the first instant in [data].
 * @param timeScale real-world [Duration] of one simulation time unit. Defaults to one hour.
 * @param spatialInterpolation strategy for generating a value from cells adjacent to the requested position.
 * @param missingValue strategy for generating a value when interpolation yields `null`.
 * @param temporalInterpolation strategy for blending adjacent slice values.
 *
 * @param T the type of data generated by this layer.
 *
 * @throws IllegalArgumentException if [data] is empty.
 */
open class CopernicusLayer<T>(
    private val environment: Environment<*, GeoPosition>,
    private val data: GridSnapshots<T>,
    timeOrigin: Instant? = null,
    timeScale: Duration = Duration.ofHours(1),
    private val spatialInterpolation: SpatialInterpolationStrategy<T>,
    private val missingValue: MissingValueStrategy<T>,
    private val temporalInterpolation: TemporalInterpolationStrategy<T>,
) : GeoLayer<T> {

    init {
        require(data.instants.isNotEmpty()) { "GridSnapshots is empty." }
    }

    /**
     * Constructs a [CopernicusLayer] from a local directory of data files (no network I/O).
     *
     * Builds a [CdmGridSnapshots] from [dataDirectory] and delegates to the primary constructor.
     * (Intended for integration tests with pre downloaded static NetCDF files)
     *
     * @param dataDirectory directory containing one or more homogeneous data files (same variable
     * and spatial grid, disjoint time ranges).
     * @param variable variable name inside the file (e.g. `"dis24"`, the GRIB shortName).
     * If `null`, it is auto-detected as the unique `(time, lat, lon)` variable.
     * @param measurementConverter defines how read [Double] values in the file should
     * be converted.
     */
    constructor(
        environment: Environment<*, GeoPosition>,
        dataDirectory: Path,
        variable: String? = null,
        timeOrigin: Instant? = null,
        timeScale: Duration = Duration.ofHours(1),
        spatialInterpolation: SpatialInterpolationStrategy<T>,
        missingValue: MissingValueStrategy<T>,
        temporalInterpolation: TemporalInterpolationStrategy<T>,
        measurementConverter: (Double) -> T,
    ) : this(
        environment,
        CdmGridSnapshots(dataDirectory, variable, measurementConverter),
        timeOrigin,
        timeScale,
        spatialInterpolation,
        missingValue,
        temporalInterpolation,
    )

    /**
     * Real-world instant corresponding to simulation `Time.ZERO`.
     * Equals `timeOrigin` if provided, otherwise the first instant in [data].
     */
    private val origin: Instant = timeOrigin ?: data.instants.first()

    /**
     * Conversion of real-world time instants to simulation time (as an array of `Double`).
     * The conversion occurs only during construction and takes into account the `origin`
     * and the `timeScale`.
     */
    private val sliceTimes: DoubleArray = data.instants
        .map { toSimulationTime(it, origin, timeScale) }
        .toDoubleArray()

    /**
     * Reads the simulation time, finds the adjacent time slices using [bracketIndices],
     * samples each of them using [temporalInterpolation] and [missingValue],
     * then blends the result using [temporalInterpolation].
     * If the simulation time falls outside the calculated simulation time range,
     * the returned value will refer to the first or last temporal slice.
     *
     * @param position the geographic position to query.
     * @return the interpolated or extrapolated value. `null` values correspond to
     * "missing"/"fill" values and can be propated or replaced by [missingValue].
     *
     * @throws IllegalArgumentException if the given [position] is outside the geographical area.
     */
    override fun getValue(position: GeoPosition): T? {
        val t = environment.simulationOrNull?.time?.toDouble() ?: 0.0

        /*
         * a function that retrieves the value resolved spatially for
         * the grid at a given index.
         */
        val sample = { i: Int ->
            val grid = data.grid(i)
            val isLatitudeInBounds = position.latitude in grid.latitudes.first()..grid.latitudes.last()
            val isLongitudeInBounds = position.longitude in grid.longitudes.first()..grid.longitudes.last()

            require(isLatitudeInBounds && isLongitudeInBounds) {
                "GeoPosition out of bounds: requested value at (lat: ${position.latitude}, " +
                    "long: ${position.longitude}) but the bounding box is lat: [${grid.latitudes.first()}, " +
                    "${grid.latitudes.last()}], long: [${grid.longitudes.first()}, ${grid.longitudes.last()}]"
            }

            val interpolatedValue = spatialInterpolation.valueAt(grid, position)
            interpolatedValue ?: missingValue.value()
        }

        /*
         * the simulation time is outside the calculated simulation time range.
         * Returns the first or the last spatially resolved value.
         */
        if (t < sliceTimes.first()) {
            return sample(0)
        } else if (t > sliceTimes.last()) {
            return sample(sliceTimes.lastIndex)
        }

        // the indices of the spatial slices that enclose time t.
        val (sliceIndexBefore, sliceIndexAfter) = bracketIndices(sliceTimes, t)

        // the time t falls exactly on a slice.
        if (sliceIndexBefore == sliceIndexAfter) return sample(sliceIndexBefore)

        /*
         * the time t lies between two distinct slices.
         * Applies the temporal interpolation strategy between the two values measured in the slices.
         */
        val blendWeight = weight(
            sliceTimes,
            sliceIndexBefore,
            sliceIndexAfter,
            t,
        )
        return temporalInterpolation.interpolate(
            sample(sliceIndexBefore),
            sample(sliceIndexAfter),
            blendWeight,
        )
    }

    private companion object {
        private const val serialVersionUID = 1L
    }
}

/**
 * Converts a real-world [Instant] to a simulation time [Double] using millisecond precision.
 *
 * @param instant timestamp to convert.
 * @param origin the instant that maps to `0.0` in simulation time.
 * @param scale duration of one simulation time unit.
 */
private fun toSimulationTime(instant: Instant, origin: Instant, scale: Duration): Double =
    Duration.between(origin, instant).toMillis().toDouble() / scale.toMillis().toDouble()
