/*
 * Copyright (C) 2010-2026, Danilo Pianini and contributors
 * listed, for each module, in the respective subproject's build.gradle.kts file.
 *
 * This file is part of Alchemist, and is distributed under the terms of the
 * GNU General Public License, with a linking exception,
 * as described in the file LICENSE in the Alchemist distribution's top directory.
 */

package it.unibo.alchemist.model.geospatial

import it.unibo.alchemist.model.Environment
import it.unibo.alchemist.model.GeoPosition
import it.unibo.alchemist.model.geospatial.reading.CdmGridSnapshots
import it.unibo.alchemist.model.geospatial.reading.GridSnapshots
import it.unibo.alchemist.model.geospatial.strategy.bracketIndices
import it.unibo.alchemist.model.geospatial.strategy.converter.MeasurementConverter
import it.unibo.alchemist.model.geospatial.strategy.spatiotemporal.SpatioTemporalInterpolation
import it.unibo.alchemist.model.geospatial.strategy.weight
import java.nio.file.Path
import java.time.Duration
import java.time.Instant

/**
 * A [GeoLayer] that exposes a value of type [T] for any [GeoPosition] as a function
 * of the current simulation time, backed by temporal NetCDF/GRIB data.
 * On [getValue], the layer knows the perceived simulation time at that moment via
 * [Environment.simulationOrNull].
 *
 * When [getValue] is called, the two time slices that enclose the current time are selected,
 * their values are evaluated spatially and temporally via [interpolation].
 * If the simulation time falls outside the calculated simulation time range,
 * the returned value will refer to the first or last time slice of [data].
 *
 * Once the construction is complete, real-world time [Instant] are converted proportionally to
 * simulation time using [timeOrigin] and [timeScale].
 *
 * Two constructors are currently available (a third one is planned once the
 * `acquisition` subpackage is implemented. SEE THE TODO below):
 * - **Primary** (this): accepts a ready-built [GridSnapshots]; intended for unit tests.
 * - **Directory**: accepts a local [Path], builds [CdmGridSnapshots] internally (no network I/O).
 *
 * @property environment simulation environment. Used only to read the current time via [Environment.simulationOrNull].
 * @property data temporal raster series backing this layer.
 * @param timeOrigin real-world [Instant] corresponding to simulation `Time.ZERO`. Defaults to the first instant in [data].
 * @param timeScale real-world [Duration] of one simulation time unit. Defaults to one hour.
 * @param interpolation strategy for generating a value from the spatio-temporal grid slices.
 * @param converter strategy for converting the interpolated [Double] (or [Double.NaN] if missing) into the
 * target type [T].
 *
 * @param T the type of data generated by this layer.
 *
 * @throws IllegalArgumentException if [data] is empty.
 */
open class CopernicusLayer<T>(
    private val environment: Environment<*, GeoPosition>,
    private val data: GridSnapshots,
    timeOrigin: Instant? = null,
    timeScale: Duration = Duration.ofHours(1),
    private val interpolation: SpatioTemporalInterpolation,
    private val converter: MeasurementConverter<T>,
) : GeoLayer<T> {

    init {
        require(data.instants.isNotEmpty()) { "GridSnapshots is empty." }
    }

    /**
     * Constructs a [CopernicusLayer] from a local directory of data files (no network I/O).
     *
     * Builds a [CdmGridSnapshots] from [dataDirectory] and delegates to the primary constructor.
     * (Intended for integration tests with pre downloaded static NetCDF files)
     *
     * @param dataDirectory directory containing one or more homogeneous data files (same variable
     * and spatial grid, disjoint time ranges).
     * @param variable variable name inside the file (e.g. `"dis24"`).
     * If `null`, it is auto-detected as the unique `(time, lat, lon)` variable.
     * @param timeOrigin real-world [Instant] corresponding to simulation `Time.ZERO`.
     * @param timeScale real-world [Duration] of one simulation time unit.
     * @param interpolation strategy for spatio-temporal evaluation.
     * @param converter defines how read [Double] values should be converted into [T].
     */
    constructor(
        environment: Environment<*, GeoPosition>,
        dataDirectory: Path,
        variable: String? = null,
        timeOrigin: Instant? = null,
        timeScale: Duration = Duration.ofHours(1),
        interpolation: SpatioTemporalInterpolation,
        converter: MeasurementConverter<T>,
    ) : this(
        environment,
        CdmGridSnapshots(dataDirectory, variable),
        timeOrigin,
        timeScale,
        interpolation,
        converter,
    )

    /**
     * Real-world instant corresponding to simulation `Time.ZERO`.
     * Equals `timeOrigin` if provided, otherwise the first instant in [data].
     */
    private val origin: Instant = timeOrigin ?: data.instants.first()

    /**
     * Conversion of real-world time instants to simulation time (as an array of `Double`).
     * The conversion occurs only during construction and takes into account the `origin`
     * and the `timeScale`.
     */
    private val sliceTimes: DoubleArray = data.instants
        .map { toSimulationTime(it, origin, timeScale) }
        .toDoubleArray()

    /**
     * Reads the simulation time, finds the adjacent time slices using [bracketIndices],
     * and applies the spatio-temporal [interpolation] strategy.
     * If the simulation time falls outside the calculated simulation time range,
     * the returned value will refer to the first or last temporal slice.
     *
     * @param position the geographic position to query.
     * @return the interpolated or extrapolated value converted to [T].
     *
     * @throws IllegalArgumentException if the given [position] is outside the geographical area.
     */
    override fun getValue(position: GeoPosition): T {
        val t = environment.simulationOrNull?.time?.toDouble() ?: 0.0

        /*
         * The simulation time is outside the calculated simulation time range.
         * Returns the first or the last spatially resolved value.
         */
        if (t < sliceTimes.first()) {
            return sampleExactSlice(position, 0)
        } else if (t > sliceTimes.last()) {
            return sampleExactSlice(position, sliceTimes.lastIndex)
        }

        // the indices of the spatial slices that enclose time t.
        val (gridIndexBefore, gridIndexAfter) = bracketIndices(sliceTimes, t)

        // the time t falls exactly on a slice.
        if (gridIndexBefore == gridIndexAfter) return sampleExactSlice(position, gridIndexBefore)

        /*
         * the time t lies between two distinct slices.
         * Applies the spatio-temporal interpolation strategy.
         */
        val timeWeight = weight(
            sliceTimes,
            gridIndexBefore,
            gridIndexAfter,
            t,
        )

        return sample(position, gridIndexBefore, gridIndexAfter, timeWeight)
    }

    /**
     * Samples the underlying grids, delegates the math to the [interpolation] strategy,
     * and directly passes the output to the [converter].
     */
    private fun sample(position: GeoPosition, gridBeforeIndex: Int, gridAfterIndex: Int, timeWeight: Double): T {
        val gridBefore = data.grid(gridBeforeIndex)
        val gridAfter = data.grid(gridAfterIndex)

        val isLatitudeInBounds = position.latitude in gridBefore.latitudes.first()..gridBefore.latitudes.last()
        val isLongitudeInBounds = position.longitude in gridBefore.longitudes.first()..gridBefore.longitudes.last()

        require(isLatitudeInBounds && isLongitudeInBounds) {
            "GeoPosition out of bounds: requested value at (lat: ${position.latitude}, " +
                "long: ${position.longitude}) but the bounding box is lat: [${gridBefore.latitudes.first()}, " +
                "${gridBefore.latitudes.last()}], long: [${gridBefore.longitudes.first()}, ${gridBefore.longitudes.last()}]"
        }

        /*
         * The interpolation returns a Double, which might be a NaN.
         * The converter is fully responsible for mapping it to T.
         */
        return converter.convert(
            interpolation.interpolate(
                position,
                gridBefore,
                gridAfter,
                timeWeight,
            ),
        )
    }

    /**
     * Helper method to sample a single grid when the simulation time matches exactly
     * one slice.
     */
    private fun sampleExactSlice(position: GeoPosition, gridIndex: Int): T = sample(
        position,
        gridIndex,
        gridIndex,
        0.0,
    )

    private companion object {
        private const val serialVersionUID = 1L
    }
}

/**
 * Converts a real-world [Instant] to a simulation time [Double] using millisecond precision.
 *
 * @param instant timestamp to convert.
 * @param origin the instant that maps to `0.0` in simulation time.
 * @param scale duration of one simulation time unit.
 */
private fun toSimulationTime(instant: Instant, origin: Instant, scale: Duration): Double =
    Duration.between(origin, instant).toMillis().toDouble() / scale.toMillis().toDouble()
