pull_request_rules:
  - name: Auto-rebase if appropriately labeled
    conditions:
      - label=auto-update-rebase
      - -draft
      - -conflict
    actions:
      rebase:
  - name: Auto-merge if appropriately labeled
    conditions:
      - label=auto-update-merge
      - -draft
      - -conflict
    actions:
      update:
