pull_request_rules:
  - name: Auto-rebase if appropriately labeled
    conditions:
      - label=auto-update-rebase
      - -draft
      - -conflict
    actions:
      rebase:
  - name: Auto-merge if appropriately labeled
    conditions:
      - label=auto-update-merge
      - -draft
      - -conflict
    actions:
      update:
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: |
          Hi @{{author}}! :wave:
          I could not help but notice that this pull request has conflicts. :confounded:
          Could you fix it? :wrench:
          Thank you! :pray:
