sudo: required
dist: trusty
language: java
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
  - openssl aes-256-cbc -K $encrypted_9993846e3f84_key -iv $encrypted_9993846e3f84_iv -in prepare_environment.sh.enc -out prepare_environment.sh -d
  - sh prepare_environment.sh
script:
  - cd alchemist 
  - ./gradlew check projectReport uploadArchives 
  - ./gradlew fatJar
  - ./gradlew closeRepository || exit 0
