/*
 * Copyright (C) 2010-2019, Danilo Pianini and contributors listed in the main project's alchemist/build.gradle file.
 *
 * This file is part of Alchemist, and is distributed under the terms of the
 * GNU General Public License, with a linking exception,
 * as described in the file LICENSE in the Alchemist distribution's top directory.
 */
package it.unibo.alchemist.kotlin

import it.unibo.alchemist.model.implementations.times.DoubleTime
import it.unibo.alchemist.model.interfaces.Time
import javafx.application.Platform
import javafx.application.Platform.runLater
import javafx.scene.canvas.Canvas
import java.awt.Point
import java.util.concurrent.FutureTask
import java.util.concurrent.TimeUnit

/**
 * The opposite of [fold].
 *
 * @param extractor A function that provides a sequence of
 * elements given a specific element of the same type.
 * @receiver The starting element to unfold.
 * @return A sequence of [E] generated by unfolding on each
 * element provided by the [extractor] function.
 *
 * @See [fold].
 */
fun <E> E.unfold(extractor: (E) -> Sequence<E>): Sequence<E> =
    sequenceOf(this) + extractor(this).flatMap { it.unfold(extractor) }

/**
 * Creates a [Point].
 *
 * @param x the x coordinate.
 * @param y the y coordinate.
 */
fun makePoint(x: Number, y: Number) = Point(x.toInt(), y.toInt())

/**
 * Sums [this] and the given [Point].
 *
 * @param p the other point.
 */
operator fun Point.plus(p: Point): Point = Point(x + p.x, y + p.y)
/**
 * Subtracts [this] and the given [Point].
 *
 * @param p the other point.
 */
operator fun Point.minus(p: Point): Point = Point(x - p.x, y - p.y)

/**
 * Plus operator for [Time].
 */
operator fun Time.plus(other: Double): Time = plus(
    DoubleTime(
        other
    )
)

/**
 * Minus operator for [Time].
 */
operator fun Time.minus(other: Double): Time = minus(
    DoubleTime(
        other
    )
)

/**
 * Clears a given canvas.
 */
fun Canvas.clear() = graphicsContext2D.clearRect(0.0, 0.0, width, height)

private const val SYNC_RUN_LATER_TIMEOUT = 2000L

/**
 * Runs the given task on the FX thread and waits for the task to finish, returning any value the task returns.
 * Throws an exception if the task takes more than a given amount of milliseconds.
 *
 * @param timeout the time in milliseconds to wait before throwing an exception, default is 2000.
 * @param task the task to execute.
 */
fun <T : Any> syncRunLater(timeout: Long = SYNC_RUN_LATER_TIMEOUT, task: () -> T): T =
    FutureTask(task).run {
        runLater {
            run()
        }
        get(timeout, TimeUnit.MILLISECONDS)
    }

/**
 * Checks if the current thread is the FX Application thread and calls [syncRunLater] if so, otherwise runs the task.
 *
 * @param timeout the time in milliseconds to wait before throwing an exception, default is 2000.
 * @param task the task to execute.
 */
fun <T : Any> syncRunOnFXThread(timeout: Long = SYNC_RUN_LATER_TIMEOUT, task: () -> T): T =
    if (!Platform.isFxApplicationThread()) {
        syncRunLater(timeout) { task() }
    } else {
        task()
    }

/**
 * Checks if the current thread is the FX Application thread and calls [runLater] if so, otherwise runs the task.
 *
 * @param task the task to execute.
 */
fun runOnFXThread(task: () -> Unit): Unit =
    if (!Platform.isFxApplicationThread()) {
        runLater { task() }
    } else {
        task()
    }
