comments:
  EndOfSentenceFormat:
    active: true
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true
complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  NestedBlockDepth:
    threshold: 5
  TooManyFunctions:
    ignoreDeprecated: true
    ignorePrivate: true
    ignoreOverridden: true
    thresholdInInterfaces: 20
naming:
  MemberNameEqualsClassName:
    active: false
performance:
  SpreadOperator:
    active: false
style:
  MagicNumber:
    ignoreNumbers: ['-2', '-1', '0', '0.5', '1', '2', '3', '4', '10', '360.0']
  ForbiddenComment:
    allowedPatterns: 'TODO:'
