/*
 * Copyright (C) 2010-2026, Danilo Pianini and contributors
 * listed, for each module, in the respective subproject's build.gradle.kts file.
 *
 * This file is part of Alchemist, and is distributed under the terms of the
 * GNU General Public License, with a linking exception,
 * as described in the file LICENSE in the Alchemist distribution's top directory.
 */

package it.unibo.alchemist.model.layers

import it.unibo.alchemist.boundary.acquisition.CopernicusDataStoreProvider
import it.unibo.alchemist.boundary.acquisition.CopernicusRequest
import it.unibo.alchemist.boundary.acquisition.FileSystemCacheManager
import it.unibo.alchemist.boundary.utils.CdsApiRc
import it.unibo.alchemist.boundary.utils.CopernicusInputs
import it.unibo.alchemist.model.Environment
import it.unibo.alchemist.model.GeoPosition
import it.unibo.alchemist.model.geospatial.reading.EagerGridSnapshots
import it.unibo.alchemist.model.geospatial.reading.GridSnapshots
import it.unibo.alchemist.model.geospatial.reading.RasterGrid
import it.unibo.alchemist.model.geospatial.strategy.converter.MeasurementConverter
import it.unibo.alchemist.model.geospatial.strategy.spatiotemporal.SpatioTemporalInterpolation
import it.unibo.alchemist.model.geospatial.utils.bracketIndices
import it.unibo.alchemist.model.geospatial.utils.weight
import java.nio.file.Path
import kotlin.time.Duration
import kotlin.time.Instant

/**
 * A [GeoLayer] that exposes a value of type [T] for any [GeoPosition] as a function
 * of the current simulation time, backed by temporal NetCDF/GRIB data.
 * On [getValue], the layer knows the perceived simulation time at that moment via
 * [Environment.simulationOrNull].
 *
 * On [getValue], the two time slices enclosing the current time are located and handed to
 * [interpolation], which resolves them both spatially and temporally; the resulting `Double`
 * (possibly [Double.NaN]) is mapped to [T] by [converter]. Outside the covered time range the
 * value of the first or last slice is returned; outside the covered **spatial** extent
 * no extrapolation is performed and [getValue] fails.
 *
 * At construction time, real-world time [Instant]s are converted proportionally to
 * simulation time using [timeOrigin] and [timeScale].
 *
 * Three constructors are available, each one relying on the one before:
 * - **Primary**: accepts a ready-built [GridSnapshots].
 * - **Directory** (YAML): takes the path of a local directory of data files. No network, no cache,
 * no credentials. Selected from YAML by providing `dataDirectory`.
 * - **Datastore** (YAML): takes a Copernicus-family endpoint plus an opaque request, retrieves the
 * data through a local cache manager, then reads it. The only one that touches the network. Selected from
 * YAML by providing `endpoint`, `dataset` and `inputsFile`.
 *
 * @param environment simulation environment. Used only to read the current time via [Environment.simulationOrNull].
 * @param data temporal raster series backing this layer.
 * @param timeOrigin real-world [Instant] corresponding to simulation `Time.ZERO`.
 * Defaults to the first instant in [data] if `null`.
 * @param timeScale real-world [Duration] of one simulation time unit.
 * @param interpolation strategy for generating a value from the spatio-temporal time slices.
 * @param converter strategy for converting the interpolated [Double] (or [Double.NaN] if missing) into the
 * target type [T].
 * @param T the type of data generated by this layer.
 * @throws IllegalArgumentException if [data] is empty; if [timeScale] is negative or infinity.
 */
open class CopernicusLayer<T>(
    private val environment: Environment<*, GeoPosition>,
    private val data: GridSnapshots,
    timeScale: Duration,
    timeOrigin: Instant?,
    private val interpolation: SpatioTemporalInterpolation,
    private val converter: MeasurementConverter<T>,
) : GeoLayer<T> {

    init {
        require(data.instants.isNotEmpty()) { "GridSnapshots is empty." }
        require(timeScale.isPositive() && timeScale.isFinite()) { "timeScale must hold a finite positive value." }
    }

    /**
     * Conversion of real-world time instants to simulation time (as an array of `Double`).
     * The conversion occurs only during construction and takes into account the `timeOrigin`
     * and the `timeScale`.
     */
    private val sliceTimes: DoubleArray = run {
        val origin: Instant = timeOrigin ?: data.instants.first()
        data.instants
            .map { toSimulationTime(it, origin, timeScale) }
            .toDoubleArray()
    }

    /**
     * Constructs a [CopernicusLayer] reading a **local directory** of already-available data files:
     * no network I/O, no cache, no credentials.
     *
     * @param dataDirectory absolute path of a directory holding one or more homogeneous data files (same
     * variable and spatial grid).
     * @param timeScale real-world duration of one simulation time unit, as an ISO-8601 duration (e.g. `"PT6H"`).
     * @param timeOrigin real-world instant mapping to simulation time `0.0`, as an ISO-8601 instant
     * (e.g. `"2024-06-10T00:00:00Z"`). The first instant found in the data is used when `null`.
     * @param variable variable name inside the file (e.g. `"dis24"`, the GRIB shortName, not the
     * catalogue name). Auto-detected as the unique `(time, lat, lon)` variable when `null`.
     * @param interpolation strategy for spatio-temporal evaluation.
     * @param converter defines how read [Double] values are converted into [T].
     * @throws IllegalArgumentException if [timeScale] or [timeOrigin] are not valid ISO-8601
     * strings; if [timeScale] is negative or infinity; if [dataDirectory] does not hold readable,
     * homogeneous data files or if the path is not correct.
     */
    constructor(
        environment: Environment<*, GeoPosition>,
        dataDirectory: String,
        timeScale: String,
        timeOrigin: String?,
        variable: String?,
        interpolation: SpatioTemporalInterpolation,
        converter: MeasurementConverter<T>,
    ) : this(
        environment,
        EagerGridSnapshots(Path.of(dataDirectory), variable),
        Duration.parseIsoString(timeScale),
        timeOrigin?.let(Instant::parse),
        interpolation,
        converter,
    )

    /**
     * Constructs a [CopernicusLayer] that fetches (and locally caches) data from a
     * Copernicus-family datastore (CDS / EWDS / ADS) identified by [endpoint], authenticating with
     * the token found in [cdsApiRcFile].
     *
     * The cache is consulted **synchronously at construction**: on a cache hit no network call and
     * no credential is needed, on a cache miss this performs blocking network I/O before the layer
     * becomes usable.
     *
     * @param endpoint base URL of the datastore (e.g. `"https://ewds.climate.copernicus.eu/api"`).
     * @param dataset dataset identifier (e.g. `"cems-glofas-historical"`).
     * @param inputsFile absolute path of a JSON file holding the opaque request map for [dataset] at
     * [endpoint] (variables, dates, area, type, ...), passed verbatim to the datastore.
     * @param checkMd5 whether to check the MD5 digest of the downloaded asset.
     * Sometimes Copernicus stores return the correct requested assets but report an incorrect MD5,
     * so it may be useful to disable this check.
     * @param timeScale real-world duration of one simulation time unit, as an ISO-8601 duration.
     * @param timeOrigin real-world instant mapping to simulation time `0.0`, as an ISO-8601
     * instant. The first instant found in the data is used when `null`.
     * @param variable variable name inside the downloaded file. Auto-detected when `null`.
     * @param cacheDirectory asbolute path to the root of the local cache.
     * @param cdsApiRcFile absolute path of a `.cdsapirc`-formatted file holding the API token.
     * @param interpolation strategy for spatio-temporal evaluation.
     * @param converter defines how read [Double] values are converted into [T].
     * @throws IllegalArgumentException if [timeScale] or [timeOrigin] are not valid ISO-8601
     * strings; if [timeScale] is negative or infinity; if [endpoint] is not a valid URL; if any
     * path is malformed.
     * @throws IllegalStateException if the token cannot be read; if the remote job fails or times
     * out; if the downloaded asset fails its integrity check.
     */
    constructor(
        environment: Environment<*, GeoPosition>,
        endpoint: String,
        dataset: String,
        inputsFile: String,
        checkMd5: Boolean,
        timeScale: String,
        timeOrigin: String?,
        variable: String?,
        cacheDirectory: String,
        cdsApiRcFile: String,
        interpolation: SpatioTemporalInterpolation,
        converter: MeasurementConverter<T>,
    ) : this(
        environment,
        EagerGridSnapshots(
            resolveDataDirectory(
                endpoint,
                dataset,
                checkMd5,
                Path.of(inputsFile),
                Path.of(cacheDirectory),
                Path.of(cdsApiRcFile),
            ),
            variable,
        ),
        Duration.parseIsoString(timeScale),
        timeOrigin?.let(Instant::parse),
        interpolation,
        converter,
    )

    /**
     * Reads the simulation time, finds the adjacent time slices using [bracketIndices],
     * and applies the spatio-temporal [interpolation] strategy.
     * If the simulation time falls outside the calculated simulation time range,
     * the returned value will refer to the first or last temporal slice.
     *
     * @param position the geographic position to query.
     * @return the interpolated or extrapolated value converted to [T].
     * @throws IllegalArgumentException if the given [position] is outside the spatial extent.
     */
    override fun getValue(position: GeoPosition): T {
        val t = environment.simulationOrNull?.time?.toDouble() ?: 0.0
        return when {
            /*
             * the simulation time is outside the calculated simulation time range.
             * Returns the first or the last spatially resolved value.
             */
            t < sliceTimes.first() -> sampleExactSlice(position, 0)
            t > sliceTimes.last() -> sampleExactSlice(position, sliceTimes.lastIndex)
            else -> {
                // the indices of the spatial slices that enclose time t.
                val (gridIndexBefore, gridIndexAfter) = bracketIndices(sliceTimes, t)
                if (gridIndexBefore == gridIndexAfter) {
                    // the time t falls exactly on a slice.
                    sampleExactSlice(position, gridIndexBefore)
                } else {
                    /*
                     * the time t lies between two distinct slices.
                     * Applies the spatio-temporal interpolation strategy.
                     */
                    val timeWeight = weight(
                        sliceTimes,
                        gridIndexBefore,
                        gridIndexAfter,
                        t,
                    )
                    sample(position, gridIndexBefore, gridIndexAfter, timeWeight)
                }
            }
        }
    }

    /**
     * Samples the underlying grids, delegates the math to the [interpolation] strategy,
     * and directly passes the output to the [converter].
     */
    private fun sample(position: GeoPosition, gridBeforeIndex: Int, gridAfterIndex: Int, timeWeight: Double): T {
        val gridBefore = data.grid(gridBeforeIndex)
        val gridAfter = data.grid(gridAfterIndex)
        val latitudes = gridBefore.latitudes
        val longitudes = gridBefore.longitudes
        val inBounds = position.latitude in latitudes.first()..latitudes.last() &&
            position.longitude in longitudes.first()..longitudes.last()
        require(inBounds) { outOfBoundsMessage(position, gridBefore) }
        /*
         * The interpolation returns a Double, which might be NaN.
         * The converter is fully responsible for mapping it to T.
         */
        return converter.convert(interpolation.interpolate(position, gridBefore, gridAfter, timeWeight))
    }

    /**
     * Helper method to sample a single grid when the simulation time matches exactly
     * one slice.
     */
    private fun sampleExactSlice(position: GeoPosition, gridIndex: Int): T = sample(
        position,
        gridIndex,
        gridIndex,
        0.0,
    )

    private companion object {
        private const val serialVersionUID = 1L

        /**
         * Ensures the data denoted by `(dataset, inputs)` is present in the local cache rooted at
         * [cacheDirectoryRoot], downloading it from [endpoint] on a cache miss, and returns the
         * directory it lives in. The token is read from [cdsApiRcFile] lazily, so a cache hit needs
         * no credentials.
         *
         * @return the directory holding the data files, ready to be opened.
         * @throws IllegalStateException if the data cannot be produced.
         */
        private fun resolveDataDirectory(
            endpoint: String,
            dataset: String,
            checkMd5: Boolean,
            inputsFile: Path,
            cacheDirectoryRoot: Path,
            cdsApiRcFile: Path,
        ): Path {
            val provider = CopernicusDataStoreProvider(checkMd5) { CdsApiRc.readToken(cdsApiRcFile) }
            val inputs = CopernicusInputs.read(inputsFile)
            val request = CopernicusRequest(endpoint.trim().trimEnd('/'), dataset, inputs)
            return FileSystemCacheManager(provider, cacheDirectoryRoot).getOrProduce(request)
        }
    }
}

/**
 * Converts a real-world [Instant] to a simulation time [Double].
 *
 * @param instant timestamp to convert.
 * @param origin the instant that maps to `0.0` in simulation time.
 * @param scale duration of one simulation time unit.
 */
private fun toSimulationTime(instant: Instant, origin: Instant, scale: Duration): Double = (instant - origin) / scale

/**
 * Builds the failure message for a [position] falling outside the extent of [grid].
 *
 * @param position the out-of-bounds [GeoPosition].
 * @param grid the grid whose extent was exceeded.
 */
private fun outOfBoundsMessage(position: GeoPosition, grid: RasterGrid): String {
    val latitudes = grid.latitudes
    val longitudes = grid.longitudes
    return "GeoPosition out of bounds: requested (lat: ${position.latitude}, lon: ${position.longitude}) " +
        "but the bounding box is lat: [${latitudes.first()}, ${latitudes.last()}], " +
        "lon: [${longitudes.first()}, ${longitudes.last()}]"
}
