/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * http://logback.qos.ch */
    const val logback_classic: String = "ch.qos.logback:logback-classic:" + Versions.logback_classic

    const val com_eden_orchidplugin_gradle_plugin: String =
            "com.eden.orchidPlugin:com.eden.orchidPlugin.gradle.plugin:" +
            Versions.com_eden_orchidplugin_gradle_plugin

    /**
     * https://github.com/ben-manes/caffeine */
    const val caffeine: String = "com.github.ben-manes.caffeine:caffeine:" + Versions.caffeine

    /**
     * https://github.com/cb372/scalacache */
    const val scalacache_core_2_12: String = "com.github.cb372:scalacache-core_2.12:" +
            Versions.com_github_cb372

    /**
     * https://github.com/cb372/scalacache */
    const val scalacache_guava_2_12: String = "com.github.cb372:scalacache-guava_2.12:" +
            Versions.com_github_cb372

    /**
     * http://github.com/davidmoten/rtree */
    const val rtree: String = "com.github.davidmoten:rtree:" + Versions.rtree

    const val com_github_maiflai_scalatest_gradle_plugin: String =
            "com.github.maiflai.scalatest:com.github.maiflai.scalatest.gradle.plugin:" +
            Versions.com_github_maiflai_scalatest_gradle_plugin

    const val com_github_spotbugs_gradle_plugin: String =
            "com.github.spotbugs:com.github.spotbugs.gradle.plugin:" +
            Versions.com_github_spotbugs_gradle_plugin

    /**
     * https://spotbugs.github.io/ */
    const val spotbugs: String = "com.github.spotbugs:spotbugs:" + Versions.spotbugs

    /**
     * https://github.com/google/gson */
    const val gson: String = "com.google.code.gson:gson:" + Versions.gson

    /**
     * https://github.com/google/guava */
    const val guava: String = "com.google.guava:guava:" + Versions.guava

    /**
     * http://code.google.com/p/concurrentlinkedhashmap */
    const val concurrentlinkedhashmap_lru: String =
            "com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:" +
            Versions.concurrentlinkedhashmap_lru

    const val com_gradle_build_scan_gradle_plugin: String =
            "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" +
            Versions.com_gradle_build_scan_gradle_plugin

    /**
     * https://www.graphhopper.com */
    const val graphhopper_core: String = "com.graphhopper:graphhopper-core:" +
            Versions.com_graphhopper

    /**
     * https://www.graphhopper.com */
    const val graphhopper_reader_osm: String = "com.graphhopper:graphhopper-reader-osm:" +
            Versions.com_graphhopper

    /**
     * http://code.google.com/p/simplelatlng */
    const val simplelatlng: String = "com.javadocmd:simplelatlng:" + Versions.simplelatlng

    const val com_jfrog_bintray_gradle_plugin: String =
            "com.jfrog.bintray:com.jfrog.bintray.gradle.plugin:" +
            Versions.com_jfrog_bintray_gradle_plugin

    /**
     * http://www.miglayout.com/ */
    const val miglayout_swing: String = "com.miglayout:miglayout-swing:" + Versions.miglayout_swing

    /**
     * https://github.com/pinterest/ktlint */
    const val ktlint: String = "com.pinterest:ktlint:" + Versions.ktlint

    /**
     * https://github.com/uchuhimo/konf */
    const val konf: String = "com.uchuhimo:konf:" + Versions.konf

    /**
     * http://commons.apache.org/proper/commons-cli/ */
    const val commons_cli: String = "commons-cli:commons-cli:" + Versions.commons_cli

    /**
     * http://commons.apache.org/proper/commons-codec/ */
    const val commons_codec: String = "commons-codec:commons-codec:" + Versions.commons_codec

    /**
     * http://commons.apache.org/proper/commons-io/ */
    const val commons_io: String = "commons-io:commons-io:" + Versions.commons_io

    /**
     * https://github.com/codecentric/javafxsvg */
    const val javafxsvg: String = "de.codecentric.centerdevice:javafxsvg:" + Versions.javafxsvg

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://github.com/classgraph/classgraph */
    const val classgraph: String = "io.github.classgraph:classgraph:" + Versions.classgraph

    /**
     * https://javaeden.github.io/Orchid/latest/core/ */
    const val orchideditorial: String = "io.github.javaeden.orchid:OrchidEditorial:" +
            Versions.io_github_javaeden_orchid

    /**
     * https://javaeden.github.io/Orchid/latest/core/ */
    const val orchidgithub: String = "io.github.javaeden.orchid:OrchidGithub:" +
            Versions.io_github_javaeden_orchid

    /**
     * https://javaeden.github.io/Orchid/latest/core/ */
    const val orchidkotlindoc: String = "io.github.javaeden.orchid:OrchidKotlindoc:" +
            Versions.io_github_javaeden_orchid

    /**
     * https://javaeden.github.io/Orchid/latest/core/ */
    const val orchidplugindocs: String = "io.github.javaeden.orchid:OrchidPluginDocs:" +
            Versions.io_github_javaeden_orchid

    /**
     * https://javaeden.github.io/Orchid/latest/core/ */
    const val orchidsearch: String = "io.github.javaeden.orchid:OrchidSearch:" +
            Versions.io_github_javaeden_orchid

    /**
     * https://javaeden.github.io/Orchid/latest/core/ */
    const val orchidsyntaxhighlighter: String =
            "io.github.javaeden.orchid:OrchidSyntaxHighlighter:" +
            Versions.io_github_javaeden_orchid

    /**
     * https://javaeden.github.io/Orchid/latest/core/ */
    const val orchidwiki: String = "io.github.javaeden.orchid:OrchidWiki:" +
            Versions.io_github_javaeden_orchid

    /**
     * https://github.com/jenetics/jpx */
    const val jpx: String = "io.jenetics:jpx:" + Versions.jpx

    /**
     * http://www.github.com/kotlintest/kotlintest */
    const val kotlintest_runner_junit5: String = "io.kotlintest:kotlintest-runner-junit5:" +
            Versions.kotlintest_runner_junit5

    /**
     * https://scafi.github.io/ */
    const val scafi_core_2_12: String = "it.unibo.apice.scafiteam:scafi-core_2.12:" +
            Versions.scafi_core_2_12

    /**
     * http://trove4j.sf.net */
    const val trove4j: String = "net.sf.trove4j:trove4j:" + Versions.trove4j

    /**
     * http://www.antlr.org */
    const val antlr4_runtime: String = "org.antlr:antlr4-runtime:" + Versions.org_antlr

    /**
     * http://www.antlr.org */
    const val antlr4: String = "org.antlr:antlr4:" + Versions.org_antlr

    /**
     * http://commons.apache.org/proper/commons-bcel */
    const val bcel: String = "org.apache.bcel:bcel:" + Versions.bcel

    /**
     * http://commons.apache.org/proper/commons-lang/ */
    const val commons_lang3: String = "org.apache.commons:commons-lang3:" + Versions.commons_lang3

    /**
     * http://commons.apache.org/proper/commons-math/ */
    const val commons_math3: String = "org.apache.commons:commons-math3:" + Versions.commons_math3

    /**
     * http://ignite.apache.org */
    const val ignite_core: String = "org.apache.ignite:ignite-core:" + Versions.org_apache_ignite

    /**
     * http://ignite.apache.org */
    const val ignite_indexing: String = "org.apache.ignite:ignite-indexing:" +
            Versions.org_apache_ignite

    /**
     * http://ignite.apache.org */
    const val ignite_spring: String = "org.apache.ignite:ignite-spring:" +
            Versions.org_apache_ignite

    /**
     * https://groovy-lang.org */
    const val groovy: String = "org.codehaus.groovy:groovy:" + Versions.groovy

    /**
     * http://www.controlsfx.org/ */
    const val controlsfx: String = "org.controlsfx:controlsfx:" + Versions.controlsfx

    const val org_danilopianini_git_sensitive_semantic_versioning_gradle_plugin: String =
            "org.danilopianini.git-sensitive-semantic-versioning:org.danilopianini.git-sensitive-semantic-versioning.gradle.plugin:" +
            Versions.org_danilopianini_git_sensitive_semantic_versioning_gradle_plugin

    const val org_danilopianini_publish_on_central_gradle_plugin: String =
            "org.danilopianini.publish-on-central:org.danilopianini.publish-on-central.gradle.plugin:" +
            Versions.org_danilopianini_publish_on_central_gradle_plugin

    /**
     * https://github.com/DanySK/boilerplate */
    const val boilerplate: String = "org.danilopianini:boilerplate:" + Versions.boilerplate

    /**
     * https://github.com/DanySK/gson-extras */
    const val gson_extras: String = "org.danilopianini:gson-extras:" + Versions.gson_extras

    /**
     * https://github.com/DanySK/java-quadtree */
    const val java_quadtree: String = "org.danilopianini:java-quadtree:" + Versions.java_quadtree

    /**
     * https://github.com/DanySK/javalib-java7 */
    const val javalib_java7: String = "org.danilopianini:javalib-java7:" + Versions.javalib_java7

    /**
     * https://github.com/DanySK/jirf */
    const val jirf: String = "org.danilopianini:jirf:" + Versions.jirf

    /**
     * https://github.com/DanySK/listset */
    const val listset: String = "org.danilopianini:listset:" + Versions.listset

    /**
     * https://github.com/DanySK/thread-inheritable-resource-loader */
    const val thread_inheritable_resource_loader: String =
            "org.danilopianini:thread-inheritable-resource-loader:" +
            Versions.thread_inheritable_resource_loader

    const val org_jetbrains_dokka_gradle_plugin: String =
            "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:" +
            Versions.org_jetbrains_dokka_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://github.com/JetBrains/java-annotations */
    const val annotations: String = "org.jetbrains:annotations:" + Versions.annotations

    /**
     * http://www.jgrapht.org */
    const val jgrapht_core: String = "org.jgrapht:jgrapht-core:" + Versions.jgrapht_core

    const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String =
            "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin:" +
            Versions.org_jlleitschuh_gradle_ktlint_gradle_plugin

    const val jool_java_8: String = "org.jooq:jool-java-8:" + Versions.jool_java_8

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:" +
            Versions.org_junit_jupiter

    /**
     * https://github.com/mapsforge/mapsforge */
    const val mapsforge_map_awt: String = "org.mapsforge:mapsforge-map-awt:" +
            Versions.mapsforge_map_awt

    /**
     * https://openjdk.java.net/projects/openjfx/ */
    const val javafx_base: String = "org.openjfx:javafx-base:" + Versions.org_openjfx

    /**
     * https://openjdk.java.net/projects/openjfx/ */
    const val javafx_controls: String = "org.openjfx:javafx-controls:" + Versions.org_openjfx

    /**
     * https://openjdk.java.net/projects/openjfx/ */
    const val javafx_fxml: String = "org.openjfx:javafx-fxml:" + Versions.org_openjfx

    /**
     * https://openjdk.java.net/projects/openjfx/ */
    const val javafx_graphics: String = "org.openjfx:javafx-graphics:" + Versions.org_openjfx

    /**
     * https://openjdk.java.net/projects/openjfx/ */
    const val javafx_media: String = "org.openjfx:javafx-media:" + Versions.org_openjfx

    /**
     * https://openjdk.java.net/projects/openjfx/ */
    const val javafx_swing: String = "org.openjfx:javafx-swing:" + Versions.org_openjfx

    /**
     * http://parboiled.org */
    const val parboiled_java: String = "org.parboiled:parboiled-java:" + Versions.parboiled_java

    /**
     * http://pegdown.org */
    const val pegdown: String = "org.pegdown:pegdown:" + Versions.pegdown

    /**
     * http://www.protelis.org */
    const val protelis_interpreter: String = "org.protelis:protelis-interpreter:" +
            Versions.org_protelis

    /**
     * http://www.protelis.org */
    const val protelis_lang: String = "org.protelis:protelis-lang:" + Versions.org_protelis

    /**
     * https://www.scala-lang.org/ */
    const val scala_compiler: String = "org.scala-lang:scala-compiler:" + Versions.org_scala_lang

    /**
     * https://www.scala-lang.org/ */
    const val scala_library: String = "org.scala-lang:scala-library:" + Versions.org_scala_lang

    /**
     * http://www.scalatest.org */
    const val scalatest_2_12: String = "org.scalatest:scalatest_2.12:" + Versions.scalatest_2_12

    /**
     * http://www.slf4j.org */
    const val slf4j_api: String = "org.slf4j:slf4j-api:" + Versions.slf4j_api

    /**
     * http://www.snakeyaml.org */
    const val snakeyaml: String = "org.yaml:snakeyaml:" + Versions.snakeyaml
}
