import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * http://logback.qos.ch */
    const val logback_classic: String = "ch.qos.logback:logback-classic:" + Versions.logback_classic

    /**
     * https://github.com/ben-manes/caffeine */
    const val caffeine: String = "com.github.ben-manes.caffeine:caffeine:" + Versions.caffeine

    /**
     * https://github.com/cb372/scalacache */
    const val scalacache_core_2_12: String = "com.github.cb372:scalacache-core_2.12:" +
            Versions.com_github_cb372

    /**
     * https://github.com/cb372/scalacache */
    const val scalacache_guava_2_12: String = "com.github.cb372:scalacache-guava_2.12:" +
            Versions.com_github_cb372

    /**
     * http://github.com/davidmoten/rtree */
    const val rtree: String = "com.github.davidmoten:rtree:" + Versions.rtree

    /**
     * https://spotbugs.github.io/ */
    const val spotbugs: String = "com.github.spotbugs:spotbugs:" + Versions.spotbugs

    /**
     * https://github.com/google/gson */
    const val gson: String = "com.google.code.gson:gson:" + Versions.gson

    /**
     * https://github.com/google/guava */
    const val guava: String = "com.google.guava:guava:" + Versions.guava

    /**
     * http://code.google.com/p/concurrentlinkedhashmap */
    const val concurrentlinkedhashmap_lru: String =
            "com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:" +
            Versions.concurrentlinkedhashmap_lru

    const val com_gradle_build_scan_gradle_plugin: String =
            "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" +
            Versions.com_gradle_build_scan_gradle_plugin

    /**
     * https://www.graphhopper.com */
    const val graphhopper_core: String = "com.graphhopper:graphhopper-core:" +
            Versions.com_graphhopper

    /**
     * https://www.graphhopper.com */
    const val graphhopper_reader_osm: String = "com.graphhopper:graphhopper-reader-osm:" +
            Versions.com_graphhopper

    /**
     * http://code.google.com/p/simplelatlng */
    const val simplelatlng: String = "com.javadocmd:simplelatlng:" + Versions.simplelatlng

    const val gradle_bintray_plugin: String = "com.jfrog.bintray.gradle:gradle-bintray-plugin:" +
            Versions.gradle_bintray_plugin

    const val com_jfrog_bintray_gradle_plugin: String =
            "com.jfrog.bintray:com.jfrog.bintray.gradle.plugin:" +
            Versions.com_jfrog_bintray_gradle_plugin

    /**
     * http://www.miglayout.com/ */
    const val miglayout_swing: String = "com.miglayout:miglayout-swing:" + Versions.miglayout_swing

    /**
     * http://commons.apache.org/proper/commons-cli/ */
    const val commons_cli: String = "commons-cli:commons-cli:" + Versions.commons_cli

    /**
     * http://commons.apache.org/proper/commons-codec/ */
    const val commons_codec: String = "commons-codec:commons-codec:" + Versions.commons_codec

    /**
     * http://commons.apache.org/proper/commons-io/ */
    const val commons_io: String = "commons-io:commons-io:" + Versions.commons_io

    /**
     * https://github.com/codecentric/javafxsvg */
    const val javafxsvg: String = "de.codecentric.centerdevice:javafxsvg:" + Versions.javafxsvg

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val spotbugs_gradle_plugin: String =
            "gradle.plugin.com.github.spotbugs:spotbugs-gradle-plugin:" +
            Versions.spotbugs_gradle_plugin

    /**
     * https://github.com/classgraph/classgraph */
    const val classgraph: String = "io.github.classgraph:classgraph:" + Versions.classgraph

    /**
     * https://github.com/jenetics/jpx */
    const val jpx: String = "io.jenetics:jpx:" + Versions.jpx

    /**
     * http://www.github.com/kotlintest/kotlintest */
    const val kotlintest_runner_junit5: String = "io.kotlintest:kotlintest-runner-junit5:" +
            Versions.kotlintest_runner_junit5

    /**
     * https://scafi.github.io/ */
    const val scafi_core_2_12: String = "it.unibo.apice.scafiteam:scafi-core_2.12:" +
            Versions.scafi_core_2_12

    /**
     * http://junit.org */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * http://trove4j.sf.net */
    const val trove4j: String = "net.sf.trove4j:trove4j:" + Versions.trove4j

    /**
     * https://pmd.github.io/ */
    const val pmd_core: String = "net.sourceforge.pmd:pmd-core:" + Versions.net_sourceforge_pmd

    /**
     * https://pmd.github.io/ */
    const val pmd_java: String = "net.sourceforge.pmd:pmd-java:" + Versions.net_sourceforge_pmd

    /**
     * https://pmd.github.io/ */
    const val pmd_jsp: String = "net.sourceforge.pmd:pmd-jsp:" + Versions.net_sourceforge_pmd

    /**
     * https://pmd.github.io/ */
    const val pmd_plsql: String = "net.sourceforge.pmd:pmd-plsql:" + Versions.net_sourceforge_pmd

    /**
     * https://pmd.github.io/ */
    const val pmd_vm: String = "net.sourceforge.pmd:pmd-vm:" + Versions.net_sourceforge_pmd

    /**
     * https://pmd.github.io/ */
    const val pmd_xml: String = "net.sourceforge.pmd:pmd-xml:" + Versions.net_sourceforge_pmd

    /**
     * http://www.antlr.org */
    const val antlr4_runtime: String = "org.antlr:antlr4-runtime:" + Versions.org_antlr

    /**
     * http://www.antlr.org */
    const val antlr4: String = "org.antlr:antlr4:" + Versions.org_antlr

    /**
     * http://commons.apache.org/proper/commons-lang/ */
    const val commons_lang3: String = "org.apache.commons:commons-lang3:" + Versions.commons_lang3

    /**
     * http://commons.apache.org/proper/commons-math/ */
    const val commons_math3: String = "org.apache.commons:commons-math3:" + Versions.commons_math3

    /**
     * http://ignite.apache.org */
    const val ignite_core: String = "org.apache.ignite:ignite-core:" + Versions.org_apache_ignite

    /**
     * http://ignite.apache.org */
    const val ignite_indexing: String = "org.apache.ignite:ignite-indexing:" +
            Versions.org_apache_ignite

    /**
     * http://ignite.apache.org */
    const val ignite_spring: String = "org.apache.ignite:ignite-spring:" +
            Versions.org_apache_ignite

    /**
     * https://groovy-lang.org */
    const val groovy: String = "org.codehaus.groovy:groovy:" + Versions.groovy

    /**
     * http://www.controlsfx.org/ */
    const val controlsfx: String = "org.controlsfx:controlsfx:" + Versions.controlsfx

    const val org_danilopianini_build_commons_gradle_plugin: String =
            "org.danilopianini.build-commons:org.danilopianini.build-commons.gradle.plugin:" +
            Versions.org_danilopianini_build_commons_gradle_plugin

    /**
     * https://github.com/DanySK/boilerplate */
    const val boilerplate: String = "org.danilopianini:boilerplate:" + Versions.boilerplate

    /**
     * https://github.com/DanySK/build-commons */
    const val build_commons: String = "org.danilopianini:build-commons:" + Versions.build_commons

    /**
     * https://github.com/DanySK/gson-extras */
    const val gson_extras: String = "org.danilopianini:gson-extras:" + Versions.gson_extras

    /**
     * https://github.com/DanySK/java-quadtree */
    const val java_quadtree: String = "org.danilopianini:java-quadtree:" + Versions.java_quadtree

    /**
     * https://github.com/DanySK/javadoc.io-linker */
    const val javadoc_io_linker: String = "org.danilopianini:javadoc.io-linker:" +
            Versions.javadoc_io_linker

    /**
     * https://github.com/DanySK/javalib-java7 */
    const val javalib_java7: String = "org.danilopianini:javalib-java7:" + Versions.javalib_java7

    /**
     * https://github.com/DanySK/jirf */
    const val jirf: String = "org.danilopianini:jirf:" + Versions.jirf

    /**
     * https://github.com/DanySK/listset */
    const val listset: String = "org.danilopianini:listset:" + Versions.listset

    /**
     * https://github.com/DanySK/thread-inheritable-resource-loader */
    const val thread_inheritable_resource_loader: String =
            "org.danilopianini:thread-inheritable-resource-loader:" +
            Versions.thread_inheritable_resource_loader

    /**
     * https://github.com/DanySK/urlclassloader-util */
    const val urlclassloader_util: String = "org.danilopianini:urlclassloader-util:" +
            Versions.urlclassloader_util

    /**
     * http://www.jboss.org/apiviz/ */
    const val apiviz: String = "org.jboss.apiviz:apiviz:" + Versions.apiviz

    const val dokka_gradle_plugin: String = "org.jetbrains.dokka:dokka-gradle-plugin:" +
            Versions.dokka_gradle_plugin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://github.com/JetBrains/java-annotations */
    const val annotations: String = "org.jetbrains:annotations:" + Versions.annotations

    /**
     * http://www.jgrapht.org */
    const val jgrapht_core: String = "org.jgrapht:jgrapht-core:" + Versions.jgrapht_core

    const val jool_java_8: String = "org.jooq:jool-java-8:" + Versions.jool_java_8

    /**
     * https://github.com/mapsforge/mapsforge */
    const val mapsforge_map_awt: String = "org.mapsforge:mapsforge-map-awt:" +
            Versions.mapsforge_map_awt

    /**
     * http://pegdown.org */
    const val pegdown: String = "org.pegdown:pegdown:" + Versions.pegdown

    /**
     * https://github.com/Protelis/protelis-interpreter */
    const val protelis_interpreter: String = "org.protelis:protelis-interpreter:" +
            Versions.org_protelis

    /**
     * https://github.com/Protelis/protelis-lang */
    const val protelis_lang: String = "org.protelis:protelis-lang:" + Versions.org_protelis

    /**
     * http://www.scala-lang.org/ */
    const val scala_compiler: String = "org.scala-lang:scala-compiler:" + Versions.org_scala_lang

    /**
     * http://www.scala-lang.org/ */
    const val scala_library: String = "org.scala-lang:scala-library:" + Versions.org_scala_lang

    /**
     * http://www.scalatest.org */
    const val scalatest_2_12: String = "org.scalatest:scalatest_2.12:" + Versions.scalatest_2_12

    /**
     * http://www.slf4j.org */
    const val slf4j_api: String = "org.slf4j:slf4j-api:" + Versions.slf4j_api

    /**
     * http://www.snakeyaml.org */
    const val snakeyaml: String = "org.yaml:snakeyaml:" + Versions.snakeyaml
}
