import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val org_danilopianini_conrec: String = "org.danilopianini:conrec:_"

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchideditorial: String = "io.github.javaeden.orchid:OrchidEditorial:_"

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidgithub: String = "io.github.javaeden.orchid:OrchidGithub:_"

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidkotlindoc: String = "io.github.javaeden.orchid:OrchidKotlindoc:_"

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidplugindocs: String = "io.github.javaeden.orchid:OrchidPluginDocs:_"

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidsearch: String = "io.github.javaeden.orchid:OrchidSearch:_"

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidsyntaxhighlighter: String = "io.github.javaeden.orchid:OrchidSyntaxHighlighter:_"

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidwiki: String = "io.github.javaeden.orchid:OrchidWiki:_"

    const val kotlin_scripting_jsr223_embeddable: String = "org.jetbrains.kotlin:kotlin-scripting-jsr223-embeddable:_"
    /**
     * http://ignite.apache.org
     */
    const val ignite_core: String = "org.apache.ignite:ignite-core:_"

    /**
     * http://ignite.apache.org
     */
    const val ignite_indexing: String = "org.apache.ignite:ignite-indexing:_"

    /**
     * http://ignite.apache.org
     */
    const val ignite_spring: String = "org.apache.ignite:ignite-spring:_"

    /**
     * https://junit.org/junit5/
     */
    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:_"

    /**
     * https://junit.org/junit5/
     */
    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:_"

    /**
     * https://github.com/cb372/scalacache
     */
    const val scalacache_core_2_12: String = "com.github.cb372:scalacache-core_2.12:_"

    /**
     * https://github.com/cb372/scalacache
     */
    const val scalacache_guava_2_12: String = "com.github.cb372:scalacache-guava_2.12:_"

    /**
     * https://www.graphhopper.com
     */
    const val graphhopper_core: String = "com.graphhopper:graphhopper-core:_"

    /**
     * https://www.graphhopper.com
     */
    const val graphhopper_reader_osm: String = "com.graphhopper:graphhopper-reader-osm:_"

    const val org_scala_lang: String = "2.12.2" // available: "2.13.1"
    /**
     * https://www.scala-lang.org/
     */
    const val scala_compiler: String = "org.scala-lang:scala-compiler:$org_scala_lang"

    /**
     * https://www.scala-lang.org/
     */
    const val scala_library: String = "org.scala-lang:scala-library:$org_scala_lang"

    /**
     * http://www.protelis.org
     */
    const val protelis_interpreter: String = "org.protelis:protelis-interpreter:_"

    /**
     * http://www.protelis.org
     */
    const val protelis_lang: String = "org.protelis:protelis-lang:_"

    /**
     * https://openjdk.java.net/projects/openjfx/
     */
    const val javafx_base: String = "org.openjfx:javafx-base:_"

    /**
     * https://openjdk.java.net/projects/openjfx/
     */
    const val javafx_controls: String = "org.openjfx:javafx-controls:_"

    /**
     * https://openjdk.java.net/projects/openjfx/
     */
    const val javafx_fxml: String = "org.openjfx:javafx-fxml:_"

    /**
     * https://openjdk.java.net/projects/openjfx/
     */
    const val javafx_graphics: String = "org.openjfx:javafx-graphics:_"

    /**
     * https://openjdk.java.net/projects/openjfx/
     */
    const val javafx_media: String = "org.openjfx:javafx-media:_"

    /**
     * https://openjdk.java.net/projects/openjfx/
     */
    const val javafx_swing: String = "org.openjfx:javafx-swing:_"

    /**
     * http://www.antlr.org
     */
    const val antlr4: String = "org.antlr:antlr4:_"

    /**
     * http://www.antlr.org
     */
    const val antlr4_runtime: String = "org.antlr:antlr4-runtime:_"

    /**
     * https://travis-ci.org/DanySK/Thread-Inheritable-Resource-Loader-for-Java
     */
    const val thread_inheritable_resource_loader: String =
            "org.danilopianini:thread-inheritable-resource-loader:_"

    /**
     * http://code.google.com/p/concurrentlinkedhashmap
     */
    const val concurrentlinkedhashmap_lru: String =
            "com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:_"

    /**
     * http://www.github.com/kotlintest/kotlintest
     */
    const val kotlintest_runner_junit5: String = "io.kotlintest:kotlintest-runner-junit5:_"

    /**
     * https://www.eclipse.org/emf
     */
    const val org_eclipse_emf_ecore: String = "org.eclipse.emf:org.eclipse.emf.ecore:_"

    /**
     * https://github.com/mapsforge/mapsforge
     */
    const val mapsforge_map_awt: String = "org.mapsforge:mapsforge-map-awt:_"

    /**
     * http://logback.qos.ch
     */
    const val logback_classic: String = "ch.qos.logback:logback-classic:_"

    /**
     * http://www.miglayout.com/
     */
    const val miglayout_swing: String = "com.miglayout:miglayout-swing:_"

    /**
     * https://scafi.github.io/
     */
    const val scafi_core_2_12: String = "it.unibo.apice.scafiteam:scafi-core_2.12:_"

    /**
     * http://parboiled.org
     */
    const val parboiled_java: String = "org.parboiled:parboiled-java:_"

    /**
     * http://www.scalatest.org
     */
    const val scalatest_2_12: String = "org.scalatest:scalatest_2.12:_"

    /**
     * https://commons.apache.org/proper/commons-codec/
     */
    const val commons_codec: String = "commons-codec:commons-codec:_"

    /**
     * http://commons.apache.org/proper/commons-lang/
     */
    const val commons_lang3: String = "org.apache.commons:commons-lang3:_"

    /**
     * http://commons.apache.org/proper/commons-math/
     */
    const val commons_math3: String = "org.apache.commons:commons-math3:_"

    /**
     * https://groovy-lang.org
     */
    const val groovy_jsr223: String = "org.codehaus.groovy:groovy-jsr223:_"

    /**
     * https://github.com/DanySK/java-quadtree
     */
    const val java_quadtree: String = "org.danilopianini:java-quadtree:_"

    /**
     * https://github.com/DanySK/javalib-java7
     */
    const val javalib_java7: String = "org.danilopianini:javalib-java7:_"

    /**
     * https://github.com/blackears/svgSalamander
     */
    const val svgsalamander: String = "guru.nidi.com.kitfox:svgSalamander:_"

    /**
     * http://www.jgrapht.org
     */
    const val jgrapht_core: String = "org.jgrapht:jgrapht-core:_"

    /**
     * http://code.google.com/p/simplelatlng
     */
    const val simplelatlng: String = "com.javadocmd:simplelatlng:_"

    /**
     * https://github.com/JetBrains/java-annotations
     */
    const val annotations: String = "org.jetbrains:annotations:_"

    /**
     * https://github.com/DanySK/boilerplate
     */
    const val boilerplate: String = "org.danilopianini:boilerplate:_"

    /**
     * http://commons.apache.org/proper/commons-cli/
     */
    const val commons_cli: String = "commons-cli:commons-cli:_"

    /**
     * https://github.com/DanySK/gson-extras
     */
    const val gson_extras: String = "org.danilopianini:gson-extras:" + Versions.gson_extras

    const val jool_java_8: String = "org.jooq:jool-java-8:" + Versions.jool_java_8

    /**
     * https://github.com/classgraph/classgraph
     */
    const val classgraph: String = "io.github.classgraph:classgraph:" + Versions.classgraph

    /**
     * http://commons.apache.org/proper/commons-io/
     */
    const val commons_io: String = "commons-io:commons-io:" + Versions.commons_io

    /**
     * http://www.controlsfx.org/
     */
    const val controlsfx: String = "org.controlsfx:controlsfx:" + Versions.controlsfx

    /**
     * https://github.com/codecentric/javafxsvg
     */
    const val javafxsvg: String = "de.codecentric.centerdevice:javafxsvg:" + Versions.javafxsvg

    /**
     * http://www.slf4j.org
     */
    const val slf4j_api: String = "org.slf4j:slf4j-api:" + Versions.slf4j_api

    /**
     * http://www.snakeyaml.org
     */
    const val snakeyaml: String = "org.yaml:snakeyaml:" + Versions.snakeyaml

    /**
     * https://github.com/ben-manes/caffeine
     */
    const val caffeine: String = "com.github.ben-manes.caffeine:caffeine:" + Versions.caffeine

    /**
     * https://spotbugs.github.io/
     */
    const val spotbugs: String = "com.github.spotbugs:spotbugs:_"

    /**
     * https://github.com/DanySK/listset
     */
    const val listset: String = "org.danilopianini:listset:_"

    /**
     * http://pegdown.org
     */
    const val pegdown: String = "org.pegdown:pegdown:" + Versions.pegdown

    /**
     * http://trove4j.sf.net
     */
    const val trove4j: String = "net.sf.trove4j:trove4j:" + Versions.trove4j

    /**
     * https://github.com/google/guava
     */
    const val guava: String = "com.google.guava:guava:" + Versions.guava

    /**
     * http://github.com/davidmoten/rtree
     */
    const val rtree: String = "com.github.davidmoten:rtree:" + Versions.rtree

    /**
     * https://commons.apache.org/proper/commons-bcel
     */
    const val bcel: String = "org.apache.bcel:bcel:" + Versions.bcel

    /**
     * https://github.com/google/gson
     */
    const val gson: String = "com.google.code.gson:gson:" + Versions.gson

    /**
     * https://github.com/DanySK/jirf
     */
    const val jirf: String = "org.danilopianini:jirf:" + Versions.jirf

    /**
     * https://github.com/uchuhimo/konf
     */
    const val konf: String = "com.uchuhimo:konf:" + Versions.konf

    /**
     * https://github.com/jenetics/jpx
     */
    const val jpx: String = "io.jenetics:jpx:" + Versions.jpx
}
