/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {

    const val jirf: String = "0.2.1"

    const val konf: String = "0.13.3" // available: "0.20.0"

    const val jpx: String = "1.5.3" // available: "1.6.0"

}
