site:
  about:
    siteName: The Alchemist Simulator
    siteDescription: An extensible simulator for doing science and engineering in pervasive, bio-inspired, and aggregate computing.
Editorial:
  primaryColor: '#169C2D'
  social:
    github: 'AlchemistSimulator/Alchemist'
  menu:
    - type: link
      title: Home
      url: '/'
    - type: 'separator'
      title: 'Documentation'
    - type: 'wiki'
    - type: 'separator'
      title: 'API Docs'
    - type: "kotlindocPackages"
      title: All Packages
    - type: "kotlindocClasses"
      title: All Classes
    - type: "kotlindocClassLinks"
      includeItems: true
  extraCss:
    - 'assets/css/pygments.scss'
allPages:
  components:
    - type: 'pageContent'
    - type: "prism"
      githubTheme: 'ghcolors'
      languages:
        - kotlin
        - java
        - groovy
        - yaml
        - asciidoc
        - markdown
        - python
