name: automerge
on:
  push:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
  schedule:
    - cron: '0 0 * * *'
  status:
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "DanySK/yaagha@0.1.1"
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOMERGE_TOKEN }}"
          MERGE_FORKS: "false"
          MERGE_LABELS: "version-upgrade"
          BLOCK_LABELS: "blocked,wontfix,invalid"
          MERGE_METHOD: "rebase"
          CLOSE_ON_CONFLICT: "true"
          DELETE_BRANCH_ON_CLOSE: "true"
          GIT_USER_NAME: "Danilo Pianini"
          GIT_USER_EMAIL: "danilo.pianini@gmail.com"
