name: automerge
on:
  push:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
  schedule:
    - cron: '0 0 * * *'
  status:
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOMERGE_TOKEN }}"
          MERGE_LABELS: "version-upgrade"
          MERGE_REMOVE_LABELS: ""
          MERGE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FILTER_AUTHOR: "DanySK"
          MERGE_FORKS: "false"
          UPDATE_LABELS: "version-upgrade"
          UPDATE_METHOD: "rebase"
