on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}

jobs:
  check-for-rebase:
    uses: DanySK/workflows/.github/workflows/rebase-on-comment.yml@master
    secrets:
      token: ${{ secrets.WORKFLOW_TOKEN }}
