/*
 * Copyright (C) 2010-2026, Danilo Pianini and contributors
 * listed, for each module, in the respective subproject's build.gradle.kts file.
 *
 * This file is part of Alchemist, and is distributed under the terms of the
 * GNU General Public License, with a linking exception,
 * as described in the file LICENSE in the Alchemist distribution's top directory.
 */

/* Generated By:JavaCC: Do not edit this line. Token.java Version 5.0 */
/* JavaCCOptions:TOKEN_EXTENDS=,KEEP_LINE_COL=null,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package it.unibo.alchemist.model.sapere.dsl.parser;

//CHECKSTYLE:OFF

/**
 * A token of the SAPERE math-expression grammar, as produced by {@link ExpTokenManager}.
 * Tokens form a singly linked stream through {@link #next}.
 */
@SuppressWarnings("PMD")
public class Token {

    /**
     * The kind of this token, as one of the token identifiers declared in {@link ExpConstants}.
     */
    public int kind;

    /** The line number of the first character of this Token. */
    public int beginLine;
    /** The column number of the first character of this Token. */
    public int beginColumn;
    /** The line number of the last character of this Token. */
    public int endLine;
    /** The column number of the last character of this Token. */
    public int endColumn;

    /**
     * The string image of the token.
     */
    public String image;

    /**
     * The next regular token of the input stream, or {@code null} if this is the last token or the token manager
     * has not read beyond it yet.
     */
    public Token next;

    /**
     * The last special token between the preceding regular token and this one, or {@code null} if there is none.
     * Special tokens are chained backwards through this field. The math-expression grammar declares no special
     * tokens, so this field is always {@code null}.
     */
    public Token specialToken;

    /**
     * An optional semantic value attached to this token, distinct from its {@link #image}.
     * Subclasses carrying a value override this method.
     *
     * @return the semantic value of this token; {@code null} by default
     */
    public Object getValue() {
        return null;
    }

    /**
     * Builds a token with kind {@code 0} and no image.
     */
    public Token() {
    }

    /**
     * Builds a token of the given kind with no image.
     *
     * @param kind the token kind, as declared in {@link ExpConstants}
     */
    public Token(final int kind) {
        this(kind, null);
    }

    /**
     * Builds a token of the given kind and image.
     *
     * @param kind the token kind, as declared in {@link ExpConstants}
     * @param image the source text matched by this token
     */
    public Token(final int kind, final String image) {
        this.kind = kind;
        this.image = image;
    }

    /**
     * @return the image of this token
     */
    @Override
    public String toString() {
        return image;
    }

    /**
     * Factory used by {@link ExpTokenManager} to create tokens. Every kind currently maps to a plain {@link Token};
     * a kind-specific subclass can be returned by adding a case to the switch.
     *
     * @param ofKind the token kind, as declared in {@link ExpConstants}
     * @param image the source text matched by the token
     * @return a new token of the given kind and image
     */
    public static Token newToken(final int ofKind, final String image) {
        return new Token(ofKind, image);
    }

    /**
     * Factory for tokens without an image.
     *
     * @param ofKind the token kind, as declared in {@link ExpConstants}
     * @return a new token of the given kind with no image
     */
    public static Token newToken(final int ofKind) {
        return newToken(ofKind, null);
    }

}
/*
 * JavaCC - OriginalChecksum=3bb8e9c96b6fdfe0d187a7fcc8b4ef1c (do not edit this
 * line)
 */
